Feat: ClipStartPage
MTVS-Noblesse/Triplay-frontend pull request #9
Opened 2024-08-28 08:34 UTC by Hexeong

## ⭐Key Changes
> 핵심 변경 사항에 대해서 적어주세요.
1. ClipStartPage view

<br>

## 📌Issue
> 닫을 issue 번호 : resolved #4

<br>

## 🩼Branch
> 반영 branch feat-4 -> dev

<br>

## 👪To Reviewers
> reviewer에게 하고 싶은 말을 적어주세요.

2024-08-29 04:15 UTC, lsy1307 requested changes

2024-08-29 04:15 UTC, lsy1307 commented on src/assets/images/clipStartPage/plusCircleButton.jpg
svg로 바꾸는 것을 추천 드려요

2024-08-29 04:15 UTC, lsy1307 commented on src/pages/ClipStartPage.jsx
> +  const [images, setImages] = useState(["해윙", "해윙", "해윙","해윙", "해윙", "해윙","해윙", "해윙", "해윙"]);
테스트 데이터는 지우고 push해주세요

2024-08-29 04:15 UTC, lsy1307 commented on src/pages/ClipStartPage.jsx
> +    gap: 10px;
rem

2024-08-30 06:05 UTC, Hexeong commented on src/assets/images/clipStartPage/plusCircleButton.jpg
테스트용 button img라 추후에 전역 font 설정시에 해결 예정

2024-08-30 06:05 UTC, Hexeong commented on src/pages/ClipStartPage.jsx
> +  const [images, setImages] = useState(["해윙", "해윙", "해윙","해윙", "해윙", "해윙","해윙", "해윙", "해윙"]);
해결 완료

2024-08-30 06:08 UTC, Hexeong commented on src/pages/ClipStartPage.jsx
> +    gap: 10px;
해결 완료

2024-08-30 07:27 UTC, lsy1307 approved these changes

2024-08-30 07:28 UTC, merged